### ISSUE TITLE
可以补充一下技术栈吗？看了半天愣是没看懂怎么运行的

### ISSUE THREAD

**Issue by JGMa-java** [datageartech/datagear#17]
你好作者，你得作品很棒，让我很想去看懂源码，但是好像和常用的架构不太一样，让我疑惑是不是用了定制的框架，或者要是能有一个项目的技术栈，架构图，这将对了解项目有很大的帮助

**Comment by datageartech** [comment]
感谢关注！
已在README.md中补充了技术栈，另参考下面的模块介绍。
