### ISSUE TITLE
SQL参数为空时报错

### ISSUE THREAD

**Issue by clearcode1124** [datageartech/datagear#20]
参数为不必填，运行时报错
![image](https://user-images.githubusercontent.com/46983983/207267563-cf7f9e85-5230-4171-889c-96abe1213a79.png)

![image](https://user-images.githubusercontent.com/46983983/207267499-8518257d-17b1-4651-850f-fa23dd3d064a.png)

**Comment by datageartech** [comment]
对于非必填参数，需要使用`<#if 参数名??></#if>`的语法进行判断，官网文档【定义数据集】章节已经补充了相关说明
