### ISSUE TITLE
关于是否存在可被外界调用的API的疑问咨询

### ISSUE THREAD

**Issue by sunshinenny** [datageartech/datagear#21]
尊敬的开发您好：
我们现在想基于您的平台，做一个内部不商用的数据展示平台。要求是有上传、编辑图表功能

我看完了文档，没看到可以外部调用的API（如Java访问对应端口，传递看板ID`xxxx`，得到此看板的对应数据，然后可以调用替换接口，传递图表ID`yyyyy`，将看板的指定图表设置为新传入的`yyyy`，进而实现使用 Java 替换看板内容）

如果有的话，可以麻烦您指点位置吗？

或者请问有开发此类接口的计划吗？

感谢🙏

**Comment by datageartech** [comment]
感谢关注！
目前版本还没有可在外部调用的相关API，不过在看板页面里可以通过JS动态加载图表，具体参考官网文档【异步加载图表】章节
