### ISSUE TITLE
无法显示hive的表

### ISSUE THREAD

**Issue by ConradWen** [datageartech/datagear#22]
现象描述：无法显示出hive的表
安装环境：java1.8,win10
（1）Hive是CDH6.0.0的版本，hive-common-2.1.1，驱动是从Cloudera官网下载的HiveJDBC-2.6.19.1022中的ClouderaHiveJDBC42-2.6.19.1022，驱动包为HiveJDBC42.jar，使用的类名为com.cloudera.hive.jdbc.HS2Driver
![图片](https://user-images.githubusercontent.com/69459423/215260243-4515d0fe-c2b1-4ad5-ad7b-085b09b38514.png)

（2）确定驱动包是上传成功的

（3）配置好数据驱动后，点击测试，测试通过，点击数据源，无法显示出数据库的表（有几率报错：无法解析表结构）
![图片](https://user-images.githubusercontent.com/69459423/215260359-98f3ea1a-37dd-4018-896f-7da42f21887d.png)
![图片](https://user-images.githubusercontent.com/69459423/215260574-b740d53c-7122-448f-b0dc-022d99ab391e.png)

（4）在数据源中无法显示表，但是在数据集中可以通过sql查询到表
![图片](https://user-images.githubusercontent.com/69459423/215260442-4ed8d0c2-9b26-4cbd-a8b5-79fbd55ac9bc.png)

（5）在看板中也能正常显示

**Comment by datageartech** [comment]
对于某些类型的数据源，系统默认的数据表过滤规则可能不适用，导致无法显示任何数据表。
新发布的5.0.0版本，可以通过在config/application.properties配置文件中开启dbmeta.tabletypes*配置项自定义数据表过滤规则。 选中数据源条目后，点击右上角下拉菜单中的【数据库信息】条目，可以查看其定义的表类型。
