### ISSUE TITLE
箱型图的数据集如何定义？

### ISSUE THREAD

**Issue by antbuster** [datageartech/datagear#27]
你好，
请问箱型图的数据集如何定义？
定义方式和Echarts有很大区别，能举个例子吗

**Comment by datageartech** [comment]
新建图表选择图表类型后，右侧有提示图标。
箱形图通常由两个或以上数据集组成：箱形数据集、异常值数据集（可选）。
箱形数据集应设置如下数据标记：名称、最小值、下四分位数-Q1、中位数-Q2、上四分位数-Q3、最大值、类别（可选）。
异常值数据集应设置如下数据标记：名称、数值、类别（可选）。
